<a href="https://colab.research.google.com/github/mekhiya/pytorch-playground/blob/main/00_pytorch_tensors_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print("Hello I'm excited to learn PyTorch!")



2.1.0+cu118
Hello I'm excited to learn PyTorch!


In [ ]:
!nvidia-smi

Thu Nov  2 01:28:30 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Scalar
scalar = torch.tensor(1001)
scalar
scalar.item()
scalar.ndim


0

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector
#vector.ndim

tensor([7, 7])

In [ ]:
# MATRIX

MATRIX = ([1,2], [4,5])
#MATRIX[1]
MATRIX

([1, 2], [4, 5])

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7866, 0.9384, 0.1700, 0.5181],
        [0.1604, 0.2377, 0.2979, 0.9003],
        [0.6609, 0.4120, 0.0508, 0.8256]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor[0,1]

tensor(0.9384)

In [ ]:
### Create a range of tensors and tensors-1
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
new_range_1 = torch.range(start=0, end=1000, step=8)
new_range_1

<ipython-input-12-300443ff774a>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  new_range_1 = torch.range(start=0, end=1000, step=8)


tensor([   0.,    8.,   16.,   24.,   32.,   40.,   48.,   56.,   64.,   72.,
          80.,   88.,   96.,  104.,  112.,  120.,  128.,  136.,  144.,  152.,
         160.,  168.,  176.,  184.,  192.,  200.,  208.,  216.,  224.,  232.,
         240.,  248.,  256.,  264.,  272.,  280.,  288.,  296.,  304.,  312.,
         320.,  328.,  336.,  344.,  352.,  360.,  368.,  376.,  384.,  392.,
         400.,  408.,  416.,  424.,  432.,  440.,  448.,  456.,  464.,  472.,
         480.,  488.,  496.,  504.,  512.,  520.,  528.,  536.,  544.,  552.,
         560.,  568.,  576.,  584.,  592.,  600.,  608.,  616.,  624.,  632.,
         640.,  648.,  656.,  664.,  672.,  680.,  688.,  696.,  704.,  712.,
         720.,  728.,  736.,  744.,  752.,  760.,  768.,  776.,  784.,  792.,
         800.,  808.,  816.,  824.,  832.,  840.,  848.,  856.,  864.,  872.,
         880.,  888.,  896.,  904.,  912.,  920.,  928.,  936.,  944.,  952.,
         960.,  968.,  976.,  984.,  992., 1000.])

In [ ]:
###Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0,2,0,4,5], dtype=None)
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0,2,0,4,5], dtype=torch.float32, device=None, requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0,2,0,4,5], dtype=torch.float16, device=None, requires_grad=False)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9.,  4.,  0., 16., 25.])

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9.,  4.,  0., 16., 25.])

### tensor.dtype

tensor.shape

tensor.device

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7619, 0.2388, 0.9488, 0.0346],
        [0.0607, 0.4527, 0.3997, 0.3772],
        [0.8191, 0.1569, 0.5007, 0.9699]])

In [ ]:
print(some_tensor)
print(f"Datattype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device of tensor: {some_tensor.device}")

tensor([[0.7619, 0.2388, 0.9488, 0.0346],
        [0.0607, 0.4527, 0.3997, 0.3772],
        [0.8191, 0.1569, 0.5007, 0.9699]])
Datattype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device of tensor: cpu


In [ ]:
torch.matmul(torch.rand(2,3) , torch.rand(3,4))

tensor([[0.1626, 0.9575, 0.8800, 1.0209],
        [0.1780, 0.5088, 0.6103, 0.7442]])

In [ ]:
torch.rand(2,3)

tensor([[0.4645, 0.9349, 0.0871],
        [0.7210, 0.9192, 0.1239]])

In [ ]:
torch.matmul(torch.tensor([[1, 2, 3],
        [4, 5, 6]]),
            torch.tensor([[7, 10],
        [8, 11],
        [9, 12]]))

tensor([[ 50,  68],
        [122, 167]])

In [ ]:
tensor_A =  torch.tensor([[7, 10],
        [8, 11],
        [9, 12]])
tensor_A

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_A.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
print(f"Original shapes: tensor_A ={tensor_A.shape}")

Original shapes: tensor_A =torch.Size([3, 2])


In [ ]:
print(f"Transpose shapes: tensor_A ={tensor_A.T.shape}")

Transpose shapes: tensor_A =torch.Size([2, 3])


In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), torch.max(x) , torch.sum(x)

(tensor(0), tensor(90), tensor(450))

In [ ]:
x.min(), x.max() , x.sum()

(tensor(0), tensor(90), tensor(450))

In [ ]:
# create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [ ]:
x[0], x[7]

(tensor(0), tensor(70))

In [ ]:
new_x = torch.arange(1.,10.)
new_x, new_x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
reshaped_x = new_x.reshape(3,3)
reshaped_x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
z = x.view(1,10)
z, z.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [ ]:
z[:, 1] = 55
z, x

(tensor([[ 0, 55, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([ 0, 55, 20, 30, 40, 50, 60, 70, 80, 90]))

In [ ]:
stacked_x = torch.stack([x,x,x,x], dim=1)
stacked_x, stacked_x.shape

(tensor([[ 0,  0,  0,  0],
         [55, 55, 55, 55],
         [20, 20, 20, 20],
         [30, 30, 30, 30],
         [40, 40, 40, 40],
         [50, 50, 50, 50],
         [60, 60, 60, 60],
         [70, 70, 70, 70],
         [80, 80, 80, 80],
         [90, 90, 90, 90]]),
 torch.Size([10, 4]))

In [ ]:
a = torch.arange(1.,13.)
a

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
v = a.view(4,3)
v, v.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [ ]:
new_v = v.squeeze(dim=1)
new_v, new_v.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [ ]:
new_b = torch.rand([2,3])
new_b, new_b.shape

(tensor([[0.4487, 0.4115, 0.4874],
         [0.2085, 0.9603, 0.0769]]),
 torch.Size([2, 3]))

In [ ]:
new_bb = new_b.squeeze()
new_bb, new_bb.shape

(tensor([[0.4487, 0.4115, 0.4874],
         [0.2085, 0.9603, 0.0769]]),
 torch.Size([2, 3]))

In [ ]:
x_original = torch.rand(size=(2,3))
x_permuted = x_original.permute(1,0)
x_original.shape, x_permuted.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
x_original

tensor([[0.4037, 0.6565, 0.8088],
        [0.4435, 0.2845, 0.9270]])

In [ ]:
x_original[:,2]

tensor([0.8088, 0.9270])

In [ ]:
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"random_tensor_A is : \n{random_tensor_A}")
print(f"random_tensor_B is : \n{random_tensor_B}")
print(f"Equal check : \n{random_tensor_A == random_tensor_B}")




random_tensor_A is : 
tensor([[0.5636, 0.7428, 0.0958, 0.6391],
        [0.4936, 0.3614, 0.8955, 0.4455],
        [0.5016, 0.7443, 0.3756, 0.9221]])
random_tensor_B is : 
tensor([[0.2104, 0.7920, 0.3452, 0.8350],
        [0.7519, 0.4405, 0.4317, 0.4458],
        [0.8745, 0.5240, 0.7799, 0.8360]])
Equal check : 
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"random_tensor_C is : \n{random_tensor_C}")
print(f"random_tensor_D is : \n{random_tensor_D}")
print(f"Equal check : \n{random_tensor_C == random_tensor_D}")



random_tensor_C is : 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
random_tensor_D is : 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Equal check : 
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

Thu Nov  2 01:28:31 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1,2,3], device="cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# device = "cuda" if torch.cuda.is_available() else "cpu"

tensorAAA = torch.tensor([1,2,3])
tensorAAA, tensorAAA.device

tensor_on_gpu = tensorAAA.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])